/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * GSAMGuiPanel.java
 *
 * Created on Sep 22, 2010, 1:52:49 PM
 */
package model.gui;

import util.ImageUtility;
import java.awt.image.BufferedImage;
import javax.swing.JTextField;

/**
 *
 * @author jparker5
 */
public class GSAMGuiPanel extends javax.swing.JPanel implements GSAMGui {

    private final LiveUpdateChart numSickChart;

    private final LiveUpdateChart totalSickChart;
    
    private final LiveUpdateChart numOnAntiviralDrugs;
    
    private final LiveUpdateChart numVaccinated;

    /**
     * Creates new form GSAMGuiPanel
     */
    public GSAMGuiPanel() {

        this.numSickChart = new LiveUpdateChart("Number Currently Sick", "Time", "Number Currently Sick");
        this.totalSickChart = new LiveUpdateChart("Total Infected", "Time", "Total Infected");

        this.numOnAntiviralDrugs = new LiveUpdateChart("Number Currently taking Antiviral Drugs", 
                                    "Time", "Number Currently taking Antiviral Drugs");
        this.numVaccinated = new LiveUpdateChart("Number Currently Vaccinated", 
                                    "Time", "Number Currently Vaccinated");
                
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mapPanel = new javax.swing.JPanel();
        numSickPanel = this.numSickChart.getChart();
        totalSickPanel = this.totalSickChart.getChart();
        configStatePanel = new javax.swing.JPanel();
        r0Label = new javax.swing.JLabel();
        socialDistLabel = new javax.swing.JLabel();
        antiviralLabel = new javax.swing.JLabel();
        vaccinationLabel = new javax.swing.JLabel();
        informationLabel = new javax.swing.JLabel();
        r0 = new javax.swing.JTextField();
        socialDist = new javax.swing.JTextField();
        antiviralDrug = new javax.swing.JTextField();
        vaccination = new javax.swing.JTextField();
        information = new javax.swing.JTextField();
        totalVaccinatedPanel = new javax.swing.JPanel();
        totalAntiviralsPanel = new javax.swing.JPanel();

        setPreferredSize(new java.awt.Dimension(900, 600));

        mapPanel.setBorder(javax.swing.BorderFactory.createTitledBorder("Map:"));

        javax.swing.GroupLayout mapPanelLayout = new javax.swing.GroupLayout(mapPanel);
        mapPanel.setLayout(mapPanelLayout);
        mapPanelLayout.setHorizontalGroup(
            mapPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 618, Short.MAX_VALUE)
        );
        mapPanelLayout.setVerticalGroup(
            mapPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        numSickPanel.setBorder(javax.swing.BorderFactory.createTitledBorder("Number Sick"));
        numSickPanel.setToolTipText("");
        numSickPanel.setPreferredSize(new java.awt.Dimension(450, 200));
        numSickPanel.setRequestFocusEnabled(false);

        javax.swing.GroupLayout numSickPanelLayout = new javax.swing.GroupLayout(numSickPanel);
        numSickPanel.setLayout(numSickPanelLayout);
        numSickPanelLayout.setHorizontalGroup(
            numSickPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 422, Short.MAX_VALUE)
        );
        numSickPanelLayout.setVerticalGroup(
            numSickPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 222, Short.MAX_VALUE)
        );

        totalSickPanel.setBorder(javax.swing.BorderFactory.createTitledBorder("Total Infected"));
        totalSickPanel.setPreferredSize(new java.awt.Dimension(450, 200));

        javax.swing.GroupLayout totalSickPanelLayout = new javax.swing.GroupLayout(totalSickPanel);
        totalSickPanel.setLayout(totalSickPanelLayout);
        totalSickPanelLayout.setHorizontalGroup(
            totalSickPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        totalSickPanelLayout.setVerticalGroup(
            totalSickPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        configStatePanel.setBorder(javax.swing.BorderFactory.createTitledBorder("Current Configuration"));

        r0Label.setText("R0:");

        socialDistLabel.setText("Social Distance:");

        antiviralLabel.setText("Antiviral Dosages:");

        vaccinationLabel.setText("Vaccination Courses:");

        informationLabel.setText("Information:");

        r0.setEditable(false);
        r0.setPreferredSize(new java.awt.Dimension(80, 28));

        socialDist.setEditable(false);
        socialDist.setPreferredSize(new java.awt.Dimension(80, 28));

        antiviralDrug.setEditable(false);
        antiviralDrug.setPreferredSize(new java.awt.Dimension(80, 28));

        vaccination.setEditable(false);
        vaccination.setMinimumSize(new java.awt.Dimension(40, 28));
        vaccination.setPreferredSize(new java.awt.Dimension(80, 28));

        information.setEditable(false);
        information.setMinimumSize(new java.awt.Dimension(40, 28));
        information.setPreferredSize(new java.awt.Dimension(80, 28));

        javax.swing.GroupLayout configStatePanelLayout = new javax.swing.GroupLayout(configStatePanel);
        configStatePanel.setLayout(configStatePanelLayout);
        configStatePanelLayout.setHorizontalGroup(
            configStatePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(configStatePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(configStatePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(r0Label)
                    .addComponent(socialDistLabel)
                    .addComponent(antiviralLabel)
                    .addComponent(vaccinationLabel)
                    .addComponent(informationLabel))
                .addGap(18, 18, 18)
                .addGroup(configStatePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(socialDist, javax.swing.GroupLayout.DEFAULT_SIZE, 142, Short.MAX_VALUE)
                    .addComponent(r0, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(antiviralDrug, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(vaccination, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(information, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        configStatePanelLayout.setVerticalGroup(
            configStatePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(configStatePanelLayout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(configStatePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(r0Label)
                    .addComponent(r0, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(configStatePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(socialDistLabel)
                    .addComponent(socialDist, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(configStatePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(antiviralLabel)
                    .addComponent(antiviralDrug, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(configStatePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(vaccinationLabel)
                    .addComponent(vaccination, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(configStatePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(informationLabel)
                    .addComponent(information, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        totalVaccinatedPanel.setBorder(javax.swing.BorderFactory.createTitledBorder("Total Vaccinated"));
        totalVaccinatedPanel.setPreferredSize(new java.awt.Dimension(450, 200));

        javax.swing.GroupLayout totalVaccinatedPanelLayout = new javax.swing.GroupLayout(totalVaccinatedPanel);
        totalVaccinatedPanel.setLayout(totalVaccinatedPanelLayout);
        totalVaccinatedPanelLayout.setHorizontalGroup(
            totalVaccinatedPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        totalVaccinatedPanelLayout.setVerticalGroup(
            totalVaccinatedPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 222, Short.MAX_VALUE)
        );

        totalAntiviralsPanel.setBorder(javax.swing.BorderFactory.createTitledBorder("Total Antivirals"));
        totalAntiviralsPanel.setPreferredSize(new java.awt.Dimension(450, 200));

        javax.swing.GroupLayout totalAntiviralsPanelLayout = new javax.swing.GroupLayout(totalAntiviralsPanel);
        totalAntiviralsPanel.setLayout(totalAntiviralsPanelLayout);
        totalAntiviralsPanelLayout.setHorizontalGroup(
            totalAntiviralsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 422, Short.MAX_VALUE)
        );
        totalAntiviralsPanelLayout.setVerticalGroup(
            totalAntiviralsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(mapPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(configStatePanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(numSickPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 434, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(totalAntiviralsPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 434, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(totalSickPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 497, Short.MAX_VALUE)
                            .addComponent(totalVaccinatedPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 497, Short.MAX_VALUE))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(mapPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(configStatePanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(numSickPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 246, Short.MAX_VALUE)
                    .addComponent(totalSickPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 246, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(totalVaccinatedPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 246, Short.MAX_VALUE)
                    .addComponent(totalAntiviralsPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 246, Short.MAX_VALUE)))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField antiviralDrug;
    private javax.swing.JLabel antiviralLabel;
    private javax.swing.JPanel configStatePanel;
    private javax.swing.JTextField information;
    private javax.swing.JLabel informationLabel;
    private javax.swing.JPanel mapPanel;
    private javax.swing.JPanel numSickPanel;
    private javax.swing.JTextField r0;
    private javax.swing.JLabel r0Label;
    private javax.swing.JTextField socialDist;
    private javax.swing.JLabel socialDistLabel;
    private javax.swing.JPanel totalAntiviralsPanel;
    private javax.swing.JPanel totalSickPanel;
    private javax.swing.JPanel totalVaccinatedPanel;
    private javax.swing.JTextField vaccination;
    private javax.swing.JLabel vaccinationLabel;
    // End of variables declaration//GEN-END:variables

    public void setR0(String result) {
        this.r0.setText(result);
    }

    public void setInformation(String info) {
        this.information.setText(info);
    }

    public void setAntiviralDrug(String drug) {
        this.antiviralDrug.setText(drug);
    }

    public void setSocialDist(String dist) {
        this.socialDist.setText(dist);
    }

    public void setVaccination(String vaccine) {
        this.vaccination.setText(vaccine);
    }
    
    public void updateAntiviralDrugs(int numCurrentlyOnAntiviralDrugs) {
        this.numOnAntiviralDrugs.addDataPoint(numCurrentlyOnAntiviralDrugs);
    }

    public void updateVaccination(int numVaccinated) {
        this.numVaccinated.addDataPoint(numVaccinated);
    }
    
    public void updateNumSick(int numCurrentlySick) {
        this.numSickChart.addDataPoint(numCurrentlySick);
    }

    public void updateTotalSick(int totalSick) {
        this.totalSickChart.addDataPoint(totalSick);
    }

    public void updateMap(BufferedImage image) {

        int BOARDER = 15;

        //BufferedImage resized = ImageUtility.resize(
        BufferedImage resized = ImageUtility.stretch(
                image,
                mapPanel.getWidth() - 2 * BOARDER,
                mapPanel.getHeight() - 2 * BOARDER);

        //image is too small width wise
        if (resized.getWidth() < mapPanel.getWidth()) {

            int widthGap = mapPanel.getWidth() - resized.getWidth();
            mapPanel.getGraphics().drawImage(resized, BOARDER + widthGap / 2, BOARDER, this);

        } else if (resized.getHeight() < mapPanel.getHeight()) {
            //image is too small height wise
            int heightGap = mapPanel.getHeight() - resized.getHeight();

            mapPanel.getGraphics().drawImage(resized, BOARDER, BOARDER + heightGap / 2, this);

        } else {
            mapPanel.getGraphics().drawImage(resized, BOARDER, BOARDER, this);
        }
    }
}
